name: Deploy to Snowflake SPCS

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

env:
  REGISTRY: bnmbckj-vi07646.registry.snowflakecomputing.com
  IMAGE_NAME: ltc_api_repo/images/fastapi_repo/ltc-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Snowflake Registry
        run: |
          echo "${{ secrets.SNOWFLAKE_PASSWORD }}" | docker login ${{ env.REGISTRY }} \
            --username ${{ secrets.SNOWFLAKE_USER }} \
            --password-stdin
      
      - name: Build version tag
        id: version
        run: |
          VERSION=$(date +%Y%m%d-%H%M%S)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"
      
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      - name: Push to Snowflake Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          echo "✅ Image pushed successfully!"
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"
      
      - name: Deployment Instructions
        run: |
          echo "=========================================="
          echo "DEPLOYMENT INFORMATION"
          echo "=========================================="
          echo "Image Version: ${{ steps.version.outputs.version }}"
          echo "Full Image Path: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"
          echo ""
          echo "Next: Create service in Snowflake with this image"
          echo "=========================================="

